SARAS : internals.o parsenew.o  
	gcc -o SARAS sarasVersion1.0.c internals.o parsenew.o
internals.o : internals.c
	gcc -c internals.c
parsenew.o : parsenew.c
	gcc -c parsenew.c
clean : 
	rm -f internals.o parsenew.o 

	
